query PostCollection(
  $preview: Boolean
  $limit: Int
  $order: [PostOrder]
  $where: PostFilter
) {
  postCollection(
    limit: $limit
    preview: $preview
    order: $order
    where: $where
  ) {
    items {
      ...PostFields
    }
  }
}
